### ISSUE TITLE
Reproducing miou 58.6 (Initial) from Table 2

### ISSUE THREAD

**Issue by uyzhang** [linyq2117/CLIP-ES#11]
I am very grateful for your solid open-source work. I've encountered a slight issue while trying to reproduce the 58.6 metric mentioned in Table 2. I directly used 'cam_to_refine' as the value for 'cam_refined' and then executed 'eval_cam.py' to evaluate the CAM (Class Activation Maps). However, the resulting mIoU I obtained is 50. Could you please help me identify what might be causing this discrepancy?

**Comment by linyq2117** [comment]
Thanks for your interest.

You need to use `highres_cam` to reproduce 58.6 because `cam_refined` is not scaled to the original resolution. You could simply uncomment `highres` in [line 212](https://github.com/linyq2117/CLIP-ES/blob/9094660d91a52ab5e855b51be43627b8e26b5137/generate_cams_voc12.py#L212) and set `--cam_type highres` when executing `eval_cam.py`.

**Comment by uyzhang** [comment]
I have successfully achieved the result. Thank you very much for your response.
