### ISSUE TITLE
train with my own dataset

### ISSUE THREAD

**Issue by Sillyyk** [linyq2117/CLIP-ES#22]
I would like to ask how to operate if I train with my own dataset, and is there a specific process? Thank you

**Comment by Sillyyk** [comment]
My own dataset only includes images and masks

**Comment by linyq2117** [comment]
Thanks for your interest!

Our method is based on the pre-trained CLIP and requires no additional training. Which type is your dataset? If the domain is similar to CLIP, you can directly use our method by giving the intended category names. Otherwise, you may resort to other training-based methods designed for specific datasets.

**Comment by Sillyyk** [comment]
> Thanks for your interest!
> 
> 我们的方法基于预先训练的 CLIP，不需要额外的训练。您的数据集是哪种类型？如果域类似于 CLIP，您可以通过提供预期的类别名称来直接使用我们的方法。否则，您可以求助于为特定数据集设计的其他基于训练的方法。

Thank you for your reply. My dataset is a self-made image tampering dataset, which only includes the corresponding tampering images and GT. What I want to know is how to load training.

**Comment by linyq2117** [comment]
It is a little confusing. For image tampering datasets, what represents the mask. You may provide more details or examples if possible.

**Comment by linyq2117** [comment]
Closed for inactivity.
